name: 'amazon_selling_partner_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  amazon_selling_partner:
    amazon_selling_partner_schema: amazon_selling_partner_integration_tests


seeds:
  amazon_selling_partner_integration_tests:
    item_identifier:
      +column_types:
        identifier_type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
