name: 'amazon_selling_partner_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  amazon_selling_partner:
    amazon_selling_partner_schema: amazon_selling_partner_integration_tests


seeds:
  amazon_selling_partner_integration_tests:
    item_identifier:
      +column_types:
        identifier_type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    orders:
      +column_types:
        promise_response_due_date: "timestamp"
        last_update_date: "timestamp"
        purchase_date: "timestamp"
        latest_delivery_date: "timestamp"
        latest_ship_date: "timestamp"
        earliest_delivery_date: "timestamp"
        earliest_ship_date: "timestamp"